AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This is a stack where SNS publishes to SQS, that then messages the lambda
  which console.logs the message
Parameters:
  LambdaBucket:
    Type: "String"
    Default: casestack-lambda-code-dev
    AllowedValues:
      - casestack-lambda-code-dev
    Description: S3 bucket that contains lambda code
  MyMessage:
    NoEcho: 'true'
    Type: String
    Description: Message for Lambda
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
#SNS resources
  MySNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: !GetAtt 
            - MyQueue1
            - Arn
          Protocol: sqs
#SQS resources
  MyQueue1:
    Type: 'AWS::SQS::Queue'


  MyQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Id: MyQueuePolicy
        Statement:
          - Sid: Allow SQS to receive msgs from SNS
            Effect: Allow
            Principal: 
              AWS: '*'
            Action: 
              - 'sqs:SendMessage'
              - 'sqs:ReceiveMessage'
            Resource: '*'
            Condition:
              ArnEquals:
                'aws:SourceArn': !Ref MySNSTopic
      Queues:
        - !Ref MyQueue1





      

